Clarify error message for missing api key
If you accidentally make a request with a missing api key, error message is ambiguous.

```javascript
// where process.env.AIRTABLE_KEY = null
Airtable.configure({
  endpointUrl: 'https://api.airtable.com',
  apiKey: process.env.AIRTABLE_KEY
})
...
``` 

Results in the error:
```
Error: API is required to connect to Airtable
```

In my case, I had forgotten to set the env var, so this throw me on a loop to figure out what `API is required` meant.
It would be more helpful if it instead described: 
```
API Key is required to connect to Airtable
```
  })